const spanish_lang = document.querySelector(".selected-lang"),
    english_lang = document.querySelector(".lang-en"),
    lang_text = document.querySelector(".lang-text"),
    flags = document.querySelector(".flags"),
    extra_changes = document.querySelector(".extra-changes"),
    item_home = document.querySelector(".home-item"),
    item_about = document.querySelector(".about-item"),
    item_works = document.querySelector(".works-item"),
    item_contact = document.querySelector(".contact-item"),
    contact_button_home = document.querySelector(".contact-button-home"),
    scroll_text = document.querySelector(".scroll-text"),
    title_about = document.querySelector(".title-about"),
    title_works = document.querySelector(".title-works"),
    title_contact = document.querySelector(".title-contact"),
    about_description = document.querySelector(".about-description"),
    download_btn = document.querySelector(".download-cv"),
    skill_1 = document.querySelector(".skill-1"),
    skill_2 = document.querySelector(".skill-2"),
    skill_3 = document.querySelector(".skill-3"),
    extra_about = document.querySelector(".extra-about"),
    programming = document.querySelector(".programming"),
    digital_subtitle = document.querySelector(".digital-subtitle"),
    digital_house = document.querySelector(".digital-house"),
    calisthenics = document.querySelector(".calisthenics-title"),
    calisthenics_subtitle = document.querySelector(".calisthenics-subtitle"),
    calisthenics_about = document.querySelector(".calisthenics-about"),
    work_1 = document.querySelector(".work-1"),
    work_2 = document.querySelector(".work-2"),
    work_3 = document.querySelector(".work-3"),
    work_4 = document.querySelector(".work-4"),
    work_5 = document.querySelector(".work-5"),
    work_6 = document.querySelector(".work-6"),
    button_vws = document.querySelector(".view-wsite"),
    button_vws2 = document.querySelector(".view-wsite-2"),
    button_vws3 = document.querySelector(".view-wsite-3"),
    button_vws4 = document.querySelector(".view-wsite-4"),
    button_vws5 = document.querySelector(".view-wsite-5"),
    button_vws6 = document.querySelector(".view-wsite-6"),
    button_vws7 = document.querySelector(".view-wsite-7"),
    button_vc = document.querySelector(".view-code"),
    button_vc2 = document.querySelector(".view-code-2"),
    button_vc3 = document.querySelector(".view-code-3"),
    button_vc4 = document.querySelector(".view-code-4"),
    button_vc5 = document.querySelector(".view-code-5"),
    contact_subtitle = document.querySelector(".contact-subtitle"),
    contact_subtitle2 = document.querySelector(".contact-subtitle-2"),
    name_contact = document.querySelector('[name="InputName"]'),
    email_contact = document.querySelector('[name="InputEmail"]'),
    subject_contact = document.querySelector('[name="InputSubject"]'),
    message_contact = document.querySelector('[name="InputMessage"]'),
    contact_button2 = document.querySelector(".contact-button-2"),
    styleElem = document.head.appendChild(document.createElement("style"));

    // styleElem.innerHTML = "lang-en:before {border-bottom: none;}";


    // SPANISH 

spanish_lang.addEventListener("click", () => {
    lang_text.innerHTML = "Idiomas",
    lang_text.style.marginRight = "13px",
    // spanish_lang.style.borderBottom = "2px solid crimson",
    // english_lang.className="lang-en extra-changes",
    flags.style.marginRight = "22px",
    item_home.innerHTML = "<i class='icon-home'></i>Inicio",
    item_about.innerHTML = "<i class='icon-user-following'></i>Sobre mí",
    item_works.innerHTML = "<i class='icon-layers'></i>Proyectos",
    item_contact.innerHTML = "<i class='icon-bubbles'></i>Contacto",
    contact_button_home.innerHTML = "Contáctame",
    scroll_text.innerHTML = "Desplazarse",
    title_about.innerHTML = "Sobre mí",
    title_works.innerHTML = "Proyectos recientes",
    title_contact.innerHTML = "Contáctame",
    about_description.innerHTML = "Soy Sergio Rodas, Desarrollador Web de Argentina. Cuento con una gran motivación por aprender y crecer profesionalmente. Soy proactivo y me gusta trabajar en entornos desafiantes que me permitan desarrollarme.",
    download_btn.innerHTML = "Descargar CV",
    skill_1.innerHTML = "Autodidacta",
    skill_2.innerHTML = "Desarrollador Web",
    skill_3.innerHTML = "Metodologías Ágiles: SCRUM",
    extra_about.innerHTML = "Soy una persona disciplinada, y me gusta llevar una planificación. También considero muy importante mantener un equilibrio y tener buenos hábitos en todos los  aspectos de mi vida para lograr el mejor rendimiento en cada uno de ellos. A continuación algunas de mis preferencias: ↓ 👍",
    programming.innerHTML = "Programación",
    digital_subtitle.innerHTML = "Curso Digital House",
    digital_house.innerHTML = "Conocí la programación a fines de 2019, realicé un bootcamp hasta marzo de 2020. Pero fue durante la pandemia cuando me apasioné de verdad.",
    calisthenics.innerHTML = "Calistenia",
    calisthenics_subtitle.innerHTML = "Front Lever🔥",
    calisthenics_about.innerHTML = "Comencé a entrenar en 2020 de manera autodidacta y se convirtió en un hábito. Me ayuda a despejarme y ser constante, además de mejorar mi calidad de vida.",
    work_1.innerHTML = "Sitio Web creado con Python y Django desde el Backend y aplicando Mobile First desde el Frontend.",
    work_2.innerHTML = "Sitio Web informativo de una sola página, sobre Calistenia y Street Workout. Construido con HTML5, CSS y JavaScript.",
    work_3.innerHTML = "Blog creado utilizando MERN Stack (MongoDB, Express, React, NodeJS). Es una aplicación CRUD, es decir, permite crear, leer, actualizar y borrar.",
    work_4.innerHTML = "Calculadora desarrollada con JavaScript, utilizando el concepto de 'Glassmorphism' para el diseño.",
    work_5.innerHTML = "Juego de preguntas y respuestas por categorías. Las cuales son 'Los Simpson', 'Dragon Ball Z', 'Marvel', 'Animales' y 'Fútbol'. HTML5, CSS y JavaScript.",
    work_6.innerHTML = "Algunas prácticas realizadas con HTML5 y CSS. Trabajando animaciones de Scroll y Glassmorphism.",
    button_vws.innerHTML = "Ver Sitio Web",
    button_vws2.innerHTML = "Ver Sitio Web",
    button_vws3.innerHTML = "Ver Sitio Web",
    button_vws4.innerHTML = "Ver Sitio Web",
    button_vws5.innerHTML = "Ver Sitio Web",
    button_vws6.innerHTML = "Ver Sitio Web 1",
    button_vws7.innerHTML = "Ver Sitio Web 2",
    button_vc.innerHTML = "Ver Código",
    button_vc2.innerHTML = "Ver Código",
    button_vc3.innerHTML = "Ver Código",
    button_vc4.innerHTML = "Ver Código",
    button_vc5.innerHTML = "Ver Código",
    contact_subtitle.innerHTML = "Déjame tu mensaje!",
    contact_subtitle2.innerHTML = "No te gustan los formularios? Envíame un <a href='mailto:sergiorodasgonzalez@gmail.com'>correo</a>. 👋",
    name_contact.placeholder = "Tu nombre",
    name_contact.setAttribute('data-error','El nombre es requerido.'),
    email_contact.placeholder = "Tu correo electrónico",
    email_contact.setAttribute('data-error','El correo es requerido.'),
    subject_contact.placeholder = "Asunto",
    subject_contact.setAttribute('data-error','El asunto es requerido.'),
    message_contact.placeholder = "Mensaje",
    message_contact.setAttribute('data-error','El mensaje es requerido.'),
    contact_button2.innerHTML = "Enviar Mensaje";
    
    });

    // ENGLISH

english_lang.addEventListener("click", () => {
    lang_text.innerHTML = "Languages",
    lang_text.style.marginRight = "5px",
    // spanish_lang.style.borderBottom = "none",
    // english_lang.className="lang-en",
    item_home.innerHTML = "<i class='icon-home'></i>Home",
    item_about.innerHTML = "<i class='icon-user-following'></i>About",
    item_works.innerHTML = "<i class='icon-layers'></i>Portfolio",
    item_contact.innerHTML = "<i class='icon-bubbles'></i>Contact",
    contact_button_home.innerHTML = "Contact me",
    scroll_text.innerHTML = "Scroll Down",
    title_about.innerHTML = "About Me",
    title_works.innerHTML = "Recent works",
    title_contact.innerHTML = "Get In Touch",
    about_description.innerHTML = "I am Sergio Rodas, Web Developer from Argentina . I have a lot of motivation to learn and grow professionally. I am proactive and I like to work in challenging environments.",
    download_btn.innerHTML = "Download CV",
    skill_1.innerHTML = "A Self Taught Person",
    skill_2.innerHTML = "Web Development",
    skill_3.innerHTML = "Agile Methodology: SCRUM",
    extra_about.innerHTML = "I am a disciplined person, and I like to have a planning. I also consider it very important to keep a balance and have good habits in all aspects of my life to achieve the best performance in each one of them. Some of my preferences: ↓ 👍",
    programming.innerHTML = "Programming",
    digital_subtitle.innerHTML = "Course Digital House",
    digital_house.innerHTML = "I found out about the programming at the end of 2019, I did a bootcamp until March 2020. But it was during the pandemic that I really become passionate.",
    calisthenics.innerHTML = "Calisthenics",
    calisthenics_subtitle.innerHTML = "Front Lever🔥",
    calisthenics_about.innerHTML = "I started training in 2020 on a self-taught basis, and it became a habit. It helps me to clear my mind and be constant, in addition to improving my quality of life.",
    work_1.innerHTML = "Website created with Python and Django from the Backend and applying Mobile First from the Frontend.",
    work_2.innerHTML = "One-page informational website on Calisthenics and Street Workout. Built with HTML5, CSS and JavaScript.",
    work_3.innerHTML = "Blog created using MERN Stack (MongoDB, Express, React, NodeJS). It is a CRUD application, that is, it allows you to create, read, update and delete.",
    work_4.innerHTML = "Calculator developed with JavaScript, using the concept of 'Glassmorphism' for design.",
    work_5.innerHTML = "Game of questions and answers by categories. Which are 'The Simpsons', 'Dragon Ball Z', 'Marvel', 'Animals' and 'Soccer'. HTML5, CSS and JavaScript.",
    work_6.innerHTML = "Some practices done with HTML5 and CSS. Using Scroll and Glassmorphism animations.",
    button_vws.innerHTML = "View Site",
    button_vws2.innerHTML = "View Site",
    button_vws3.innerHTML = "View Site",
    button_vws4.innerHTML = "View Site",
    button_vws5.innerHTML = "View Site",
    button_vws6.innerHTML = "View Site 1",
    button_vws7.innerHTML = "View Site 2",
    button_vc.innerHTML = "View Code",
    button_vc2.innerHTML = "View Code",
    button_vc3.innerHTML = "View Code",
    button_vc4.innerHTML = "View Code",
    button_vc5.innerHTML = "View Code",
    contact_subtitle.innerHTML = "Let's talk about everything!",
    contact_subtitle2.innerHTML = "Don't like forms? Send me an <a href='mailto:sergiorodasgonzalez@gmail.com'>email</a>. 👋",
    name_contact.placeholder = "Your name",
    name_contact.setAttribute('data-error','Name is required.'),
    email_contact.placeholder = "Your email address",
    email_contact.setAttribute('data-error','Email is required.'),
    subject_contact.placeholder = "Subject",
    subject_contact.setAttribute('data-error','Subject is required.'),
    message_contact.placeholder = "Message",
    message_contact.setAttribute('data-error','Message is required.'),
    contact_button2.innerHTML = "Send Message";
    });
